### ISSUE TITLE
defining a task named `load' would shadow an existing method with that name (ArgumentError)

### ISSUE THREAD

**Issue by singpolyma** [njonsson/cape#7]
I'm using Capistrano and Rake with Rails3 and rake-rails.  I've narrowed the error down to happening when it gets to defining the cap task for Rake's `db:fixtures:load`

```
/mnt/cache/var/lib/gems/1.9.1/gems/capistrano-2.12.0/lib/capistrano/configuration/namespaces.rb:97:in `task': defining a task named `load' would shadow an existing method with that name (ArgumentError)
        from /mnt/cache/var/lib/gems/1.9.1/gems/cape-1.4.0/lib/cape/capistrano.rb:103:in `block in implement'
```

The relevant Cap code is:

```
namespace :rakesnake do
  Cape do
    mirror_rake_tasks do |env|
      env['RAILS_ENV'] = rails_env
    end
  end
end
```

**Comment by cmckni3** [comment]
I am having the same issue as @njonsson

I'm using your code above. I use `minitest` and `minitest-rails`.

``` ruby
namespace :rake_tasks do
  Cape do
    mirror_rake_tasks do |recipes|
      recipes.options[:roles] = :app
      recipes.env['RAILS_ENV'] = lambda { rails_env }

      # The mirrored Capistrano recipe for a Rake task 'foo' will be named
      # 'rake_tasks:foo_task'.
      recipes.rename do |rake_task_name|
        "#{rake_task_name}_task"
      end
    end
  end
end
```

**Comment by cmckni3** [comment]
I ended up filtering out tasks I don't want to mirror. I had to change the namespace of my rake tasks as well. It seems the namespace `system` is reserved in capistrano.
